# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None

# 项目根目录（SPEC 是 PyInstaller 内置变量，指向本文件所在目录） 
project_root = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    ['main.py'],
    pathex=[project_root],
    binaries=[],
    datas=[
        # ── 核心配置文件 ──────────────────────────────────────
        (os.path.join(project_root, 'version.py'), '.'),
        (os.path.join(project_root, 'version.json'), '.'),
        # ── 报告模板───────────────────────────────────────────
        (os.path.join(project_root, 'templates'), 'templates'),
        # ── Web UI ───────────────────────────────────────────
        (os.path.join(project_root, 'web_templates'), 'web_templates'),
        # ── i18n 国际化 ──────────────────────────────────────
        (os.path.join(project_root, 'i18n'), 'i18n'),
        # ── RAG 知识库模块 ───────────────────────────────────
        (os.path.join(project_root, 'rag'), 'rag'),
        # ── Pro 插件目录（数据源管理、规则引擎）────────────
        (os.path.join(project_root, 'pro'), 'pro'),
        # ── Pro 规则目录（YAML 配置文件）───────────────
        (os.path.join(project_root, 'pro', 'rules'), 'pro/rules'),
    ],
    hiddenimports=[
        # ── 数据库驱动 ───────────────────────────────────────
        'pymysql',
        'pymysql.connections',
        'pymysql.cursors',
        'pymysql.converters',
        'psycopg2',
        'psycopg2.extensions',
        'psycopg2.extras',
        'oracledb',
        'oracledb.basemod',
        'oracledb.driverless',
        'cx_Oracle',
        'dmpython',
        'dmPython',
        'pyodbc',
        # ── Word 报告 ────────────────────────────────────────
        'docx',
        'docxtpl',
        'docxtpl.template',
        'docxtpl.parser',
        'jinja2.ext',
        'jinja2.runtime',
        'jinja2.filters',
        'kazoo',
        'lxml',
        'lxml.etree',
        'lxml.builder',
        'lxml._elementpath',
        'xml.etree.ElementTree',
        'xml.etree.ElementPath',
        'markupsafe',
        # ── 系统资源采集 ──────────────────────────────────────
        'paramiko',
        'paramiko.transport',
        'paramiko.client',
        'paramiko.auth_handler',
        'paramiko.packet',
        'paramiko.cipher',
        'paramiko.util',
        'paramiko.hostkeys',
        'paramiko.channel',
        'psutil',
        'psutil._common',
        'psutil._pswindows',
        # ── 数据处理 ──────────────────────────────────────────
        'openpyxl',
        'openpyxl.utils',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'pandas',
        'pandas.core',
        'pandas.core.indexes',
        # ── Web UI ───────────────────────────────────────────
        'flask',
        'flask.app',
        'flask.blueprints',
        'flask.templating',
        'flask_socketio',
        'flask_socketio.emit_queue',
        'socketio',
        'socketio.base_server',
        'socketio.server',
        'socketio.manager',
        'socketio.packet',
        'engineio',
        'engineio.Server',
        'engineio.async_drivers',
        'engineio.async_drivers.threading',
        'werkzeug',
        'werkzeug.serving',
        'werkzeug.wrappers',
        'werkzeug.local',
        # ── 其他工具 ──────────────────────────────────────────
        'schedule',
        'colorama',
        'PIL',
        'PIL.Image',
        # ── 项目模块 ──────────────────────────────────────────
        'version',
        'mod_logger',
        'analyzer',
        'slow_query_analyzer',
        'db_history',
        'desensitize',
        'pdf_export',
        'index_health',
        'config_baseline',
        'main_mysql',
        'main_pg',
        'main_oracle_full',
        'main_sqlserver',
        'main_dm',
        'main_tidb',
        'web_ui',
        # ── 定时巡检 & 通知（v2.4.0+ 新增）────────────────────
        'scheduler',
        'notifier',
        'run_inspection',
        'apscheduler',
        'apscheduler.schedulers',
        'apscheduler.schedulers.background',
        'apscheduler.triggers',
        'apscheduler.triggers.cron',
        'apscheduler.triggers.date',
        'apscheduler.triggers.interval',
        'apscheduler.executors',
        'apscheduler.executors.pool',
        'pytz',
        'pytz.exceptions',
        'pytz.tzinfo',
        # ── Pro 插件模块（v2.4.0+）─────────────────────────
        'pro',
        'pro.instance_manager',
        'pro.rule_engine',
        'pro.report_score',
        'pro.version',
        'pro.backup',
        'pro.backup.base',
        'pro.backup.manager',
        'pro.backup.mysql_backup',
        'pro.backup.pg_backup',
        'pro.backup.oracle_backup',
        'pro.backup.sqlserver_backup',
        # ── REST API v1 + Auth ───────────────────────────────
        'api_v1',
        'auth',
        # ── i18n ─────────────────────────────────────────────
        'i18n',
        'i18n.zh',
        'i18n.en',
        # ── RAG 知识库模块（v2.4.0+ 新增）─────────────────
        'rag',
        'rag.manager',
        'rag.document_processor',
        'rag.embeddings',
        'rag.vector_store',
        'rag.retriever',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'scipy',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='dbcheck',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
